### ISSUE TITLE
Graphql

### ISSUE THREAD

**Issue by jimthedev** [milesj/shapeshifter#5]
Any way to support it? Also, any chance to support migrations or depreciations since types change over time?

**Comment by milesj** [comment]
I've actually talked about this somewhat with my co-workers, as we're on the path to using GraphQL.

It's a tricky problem to solve as GQL is such a divergence than say REST. However, it is on the roadmap, possibly using [introspection](http://graphql.org/docs/introspection/), just not sure when it will happen.

**Comment by milesj** [comment]
Before I look into this more, which functionality are you looking to support?

- Reading from GQL structures instead of the JSON format?
- Or generating the GQL from the JSON?
- Or both?

**Comment by milesj** [comment]
GQL support has been added.
